const fs = require('fs');
let content = fs.readFileSync('lineup.js', 'utf8');
let lineup = [];
eval(content.replace('const lineup =', 'lineup ='));

const genresMap = {
  "Ouineta": ["indie pop", "alternative dance"],
  "Yard Act": ["post-punk", "art punk", "indie rock"],
  "Guitarricadelafuente": ["spanish pop", "singer-songwriter", "acoustic"],
  "Wet Leg": ["indie rock", "post-punk", "alternative rock"],
  "Mourn": ["indie rock", "post-punk", "catalan indie"],
  "Gara Durán": ["spanish pop", "folk-pop"],
  "Dani Dicostas": ["spanish pop", "indie pop", "synthpop"],
  "Cameron Winter": ["indie rock", "singer-songwriter"],
  "Lucrecia Dalt": ["experimental", "ambient", "electronic"],
  "caroline": ["post-rock", "experimental rock", "art rock"],
  "Panda Bear": ["psychedelic pop", "experimental pop", "indie pop"],
  "Gisela João": ["fado", "portuguese folk"],
  "Men I Trust": ["indie pop", "dream pop", "bedroom pop"],
  "Oklou": ["ambient pop", "alternative r&b", "electronic"],
  "Father John Misty": ["indie folk", "singer-songwriter", "art pop"],
  "2hollis": ["hyperpop", "electronic", "underground rap"],
  "¥ØU$UK€ ¥UK1MAT$U": ["techno", "electronic", "noise"],
  "Aiko el Grupo": ["punk pop", "spanish punk", "indie pop"],
  "Ravyn Lenae": ["r&b", "neo soul", "alternative r&b"],
  "Massive Attack": ["trip hop", "electronic", "downtempo"],
  "Bad Gyal": ["dancehall", "reggaeton", "trap"],
  "Raly": ["electronic", "global club"],
  "Geese": ["post-punk", "indie rock", "art punk"],
  "Mac DeMarco": ["indie pop", "slacker rock", "jangle pop"],
  "TV Girl": ["indie pop", "lo-fi", "dream pop"],
  "Overmono": ["uk bass", "techno", "electronic"],
  "Sama Yax": ["electronic", "house", "techno"],
  "berlioz": ["lo-fi house", "electronic jazz", "house"],
  "Guedra Guedra": ["global club", "bass music", "electronic"],
  "Ahadadream": ["uk funky", "global club", "bass music"],
  "BAMBII": ["dancehall", "electronic", "jungle"],
  "Ben UFO": ["house", "techno", "uk bass"],
  "Paus": ["experimental rock", "math rock", "indie rock"],
  "The New Eves": ["folk punk", "experimental folk"],
  "Agriculture": ["black metal", "post-metal", "heavy metal"],
  "Florence Road": ["indie pop", "alternative rock"],
  "Melt-Banana": ["noise rock", "punk", "experimental rock"],
  "VVV [Trippin'you]": ["electronic", "synth-punk", "darkwave"],
  "Muna Khaled": ["ambient", "electronic"],
  "Toumba live": ["global club", "electronic", "bass music"],
  "Bclip": ["latin club", "electronic", "reggaeton"],
  "iza tkm": ["electronic", "club"],
  "DJ Playero": ["reggaeton", "latin", "urbano"],
  "xavisphone": ["electronic", "hyperpop"],
  "Proc Fiskal live": ["grime", "uk bass", "electronic"],
  "Stein": ["techno", "electronic"],
  "Rustie": ["wonky", "electronic", "uk bass"],
  "Zohar": ["techno", "experimental electronic"],
  "Mina Galán": ["electronic", "ambient"],
  "Blood Orange": ["alternative r&b", "indie pop", "synthpop"],
  "Alex G": ["indie rock", "lo-fi", "singer-songwriter"],
  "Doja Cat": ["pop", "rap", "r&b"],
  "Hypnosis Therapy": ["electronic", "korean rap", "club"],
  "Renaldo & Clara": ["catalan indie", "indie pop"],
  "LaBlackie": ["spanish rap", "trap"],
  "Skullcrusher": ["ambient folk", "indie folk", "singer-songwriter"],
  "Rojuu": ["emo trap", "spanish pop", "hyperpop"],
  "Fcukers": ["indie dance", "house", "electronic"],
  "Six Sex": ["reggaeton", "club", "neoperreo"],
  "Malibu": ["ambient", "electronic", "ethereal"],
  "Brìghde Chaimbeul": ["celtic folk", "drone", "ambient"],
  "New York": ["indie rock", "alternative rock"],
  "neska": ["electronic", "ambient"],
  "Oli XL Live": ["electronic", "uk bass", "idm"],
  "Anthony Naples": ["house", "techno", "electronic"],
  "Bombificadas": ["punk pop", "indie rock"],
  "Paco Te Quiero": ["indie pop", "spanish pop"],
  "Dharmacide": ["shoegaze", "post-punk", "dream pop"],
  "Annahstasia": ["folk", "soul", "singer-songwriter"],
  "mark william lewis": ["indie rock", "singer-songwriter", "lo-fi"],
  "Einstürzende Neubauten": ["industrial", "experimental", "avant-garde"],
  "Merzbow": ["noise", "experimental", "electronic"],
  "Pavvla": ["catalan indie", "electronic pop", "indie folk"],
  "Buscabulla": ["latin alternative", "dream pop", "electronic"],
  "Ralphie Choo": ["flamenco pop", "experimental pop", "spanish electronic"],
  "Amaarae": ["afrobeats", "alternative r&b", "pop"],
  "PinkPantheress": ["drum and bass", "uk garage", "pop"],
  "KI/KI": ["techno", "trance", "electronic"],
  "NewDad": ["indie rock", "shoegaze", "alternative rock"],
  "Ethel Cain": ["indie rock", "slowcore", "dream pop"],
  "The Cure": ["post-punk", "gothic rock", "new wave"],
  "Slowdive": ["shoegaze", "dream pop", "indie rock"],
  "Addison Rae": ["pop", "dance pop"],
  "Skrillex": ["dubstep", "electronic", "edm"],
  "Somos la Herencia": ["post-punk", "darkwave", "electronic"],
  "Rilo Kiley": ["indie rock", "indie pop", "alternative country"],
  "Role Model": ["indie pop", "bedroom pop", "pop"],
  "Jade": ["pop", "r&b"],
  "Viagra Boys": ["post-punk", "art punk", "indie rock"],
  "Malena": ["electronic", "techno"],
  "Powder": ["house", "electronic", "techno"],
  "Call Super": ["techno", "house", "electronic"],
  "DJ Koolt": ["house", "techno", "electronic"],
  "Roza Terenzi Live": ["electro", "breakbeat", "techno"],
  "Aurora Halal": ["techno", "electronic", "psychedelic"],
  "Sama’ Abdulhadi": ["techno", "electronic", "hard techno"],
  "Las Petunias": ["punk pop", "indie pop"],
  "Ósserp": ["death metal", "grindcore", "heavy metal"],
  "Water From Your Eyes": ["experimental pop", "indie rock", "art pop"],
  "Shlohmo": ["electronic", "instrumental hip hop", "bass music"],
  "Kylesa": ["sludge metal", "stoner metal", "heavy metal"],
  "Tiyumii": ["electronic", "ambient"],
  "Dj Khalipha": ["global club", "electronic"],
  "GЯEG": ["dancehall", "techno", "global club"],
  "The Avalanches DJ Set": ["plunderphonics", "electronic", "dance"],
  "Loukeman": ["house", "electronic"],
  "Brutalismus 3000": ["gabber", "techno", "punk"],
  "Brat Star DJ Set": ["club", "techno", "rap"],
  "Hannah Diamond (DJ)": ["pc music", "hyperpop", "electronic"],
  "Hekt": ["techno", "electronic"],
  "deBasement": ["techno", "bass music"],
  "Debit": ["experimental electronic", "ambient", "club"],
  "Dave P.": ["electronic", "house", "dance"],
  ".bd.": ["experimental", "electronic"],
  "Juicy Bae": ["spanish r&b", "trap", "reggaeton"],
  "Texas Is The Reason": ["emo", "post-hardcore", "punk rock"],
  "Disobey": ["punk rock", "hardcore"],
  "fakemink": ["electronic", "club"],
  "Cara Delevingne": ["pop", "electronic"],
  "Underground Resistance": ["detroit techno", "electronic", "techno"],
  "Joan La Barbara": ["avant-garde", "contemporary classical", "vocal"],
  "Matmos": ["experimental electronic", "idm"],
  "Rashad Becker": ["experimental electronic", "ambient", "noise"],
  "Mohammad Reza Mortazavi": ["world", "percussion", "traditional"],
  "Marc Piñol": ["house", "techno", "electronic"],
  "Iglooghost": ["wonky", "idm", "electronic"],
  "Amiga Date Cuenta": ["indie pop", "spanish pop"],
  "Perfecto Miserable": ["shoegaze", "dream pop"],
  "Corte!": ["post-punk", "indie rock"],
  "SVSTO": ["electronic pop", "indie pop"],
  "These New Puritans": ["art rock", "experimental rock", "post-punk"],
  "Beverly Glenn-Copeland and Elizabeth Copeland": ["ambient", "new age", "folk"],
  "Anna von Hausswolff": ["neoclassical dark wave", "experimental", "drone"],
  "Jimena Amarillo": ["spanish pop", "bedroom pop", "indie pop"],
  "Grace Ives": ["synthpop", "indie pop"],
  "rusowsky": ["bedroom pop", "lo-fi", "spanish pop"],
  "Dijon": ["alternative r&b", "indie folk", "soul"],
  "Knocked Loose": ["metalcore", "hardcore punk", "heavy metal"],
  "Peggy Gou": ["house", "electronic", "techno"],
  "Big Thief": ["indie folk", "indie rock"],
  "My Bloody Valentine": ["shoegaze", "noise pop", "dream pop"],
  "Gorillaz": ["alternative rock", "art pop", "electronic"],
  "Bestia Bebé": ["argentine indie", "indie rock"],
  "Sudan Archives": ["alternative r&b", "experimental pop", "electronic"],
  "Ashnikko": ["alt-pop", "trap", "rap"],
  "Marina": ["pop", "dance pop", "electropop"],
  "Kneecap": ["irish hip hop", "rap"],
  "M8NSE": ["electronic", "bass music"],
  "Florentino b2b dj g2g": ["reggaeton", "club", "electronic"],
  "Safety Trance Live AV": ["reggaeton", "techno", "industrial"],
  "Lechuga Zafiro & Verraco: Hyperverbena": ["latin club", "electronic", "bass music"],
  "mobilegirl": ["club", "r&b", "electronic"],
  "Mechatok Live": ["electronic pop", "club"],
  "u.r.trax Live": ["techno", "electronic", "hard techno"],
  "JASSS": ["techno", "experimental electronic", "industrial"],
  "The Sophs": ["indie rock", "alternative rock"],
  "Smerz": ["alternative r&b", "electronic", "minimal"],
  "Lambrini Girls": ["punk rock", "post-punk"],
  "Femtanyl": ["hyperpop", "breakcore", "electronic"],
  "Ninajirachi": ["electronic", "hyperpop", "club pop"],
  "Curated by SONNY": ["electronic", "club"],
  "Barry B": ["indie pop", "spanish pop"],
  "Baxter Dury": ["indie rock", "art pop", "spoken word"],
  "Little Simz": ["uk hip hop", "rap", "neo soul"],
  "The xx": ["indie pop", "dream pop", "electronic"],
  "Ven’nus": ["catalan indie", "electronic pop"],
  "Depresión Sonora": ["post-punk", "spanish indie", "darkwave"],
  "Gelli Haha": ["alternative pop", "indie pop"],
  "Touché Amoré": ["post-hardcore", "screamo", "emo"],
  "Joey Valence & Brae": ["hip hop", "rap", "boom bap"],
  "Nick León Live": ["club", "techno", "latin electronic"],
  "Ecco2k": ["cloud rap", "drain", "alternative pop"],
  "res_": ["techno", "electronic"],
  "DJ Marcelle": ["experimental", "dub", "electronic"],
  "Shackleton Live": ["dubstep", "tribal", "electronic"],
  "Beatrice M.": ["electronic", "techno", "bass music"],
  "A Guy Called Gerald Live": ["acid house", "jungle", "electronic"],
  "DJ Nobu": ["techno", "electronic", "deep techno"],
  "Greta": ["indie pop", "pop"],
  "BLOND:ISH": ["tech house", "house", "electronic"],
  "Joseph Capriati": ["techno", "tech house", "electronic"],
  "Carl Cox": ["techno", "house", "electronic"]
};

lineup = lineup.map(band => {
  const genres = genresMap[band.band] || ["electronic", "indie rock"];
  return { ...band, genres: genres };
});

const newContent = `const lineup = ${JSON.stringify(lineup, null, 2)};\n`;
fs.writeFileSync('lineup.js', newContent);
console.log('Successfully enriched all lineup bands with genres.');
