const fs = require('fs');
let content = fs.readFileSync('lineup.js', 'utf8');
let lineup = [];
eval(content.replace('const lineup =', 'lineup ='));

const descriptions = {
  "Ouineta": "AI Summary: Local favorite bringing vibrant energy and genre-blending tracks to the stage.",
  "Yard Act": "AI Summary: Celebrated for their spiky, spoken-word post-punk, critics praise their sharp social commentary and infectious groove.",
  "Guitarricadelafuente": "AI Summary: A soulful Spanish artist praised for his raw, acoustic performances and deeply emotional songwriting.",
  "Wet Leg": "AI Summary: Breakout indie rock duo known for deadpan lyrics and catchy, hook-laden anthems that charm reviewers universally.",
  "Mourn": "AI Summary: Acclaimed Catalan indie rock band known for their fierce, energetic punk-infused performances.",
  "Gara Durán": "AI Summary: Rising Spanish talent bringing poetic lyrics and captivating pop-folk melodies.",
  "Dani Dicostas": "AI Summary: Spanish pop artist recognized for her catchy, synth-driven indie pop and charismatic live presence.",
  "Cameron Winter": "AI Summary: A compelling vocalist and songwriter, bringing intimate and melodic performances to the festival.",
  "Lucrecia Dalt": "AI Summary: Experimental electronic artist whose avant-garde soundscapes are celebrated for their cinematic and eerie qualities.",
  "caroline": "AI Summary: Eight-piece post-rock ensemble delivering sprawling, improvisational pieces praised for their organic complexity.",
  "Panda Bear": "AI Summary: Animal Collective member delivering hypnotic, sample-heavy psychedelic pop. Reviews highlight his celestial vocal harmonies.",
  "Gisela João": "AI Summary: One of Portugal's leading fado singers, delivering breathtakingly emotional and traditional vocal performances.",
  "Men I Trust": "AI Summary: Beloved indie-pop trio. Critics praise their smooth, atmospheric grooves and incredibly soothing live presence.",
  "Oklou": "AI Summary: French electronic producer and vocalist known for her ethereal, ambient pop and stunningly intricate sound design.",
  "Father John Misty": "AI Summary: Acclaimed for his theatrical indie-folk and biting, satirical lyricism that critics often describe as brilliantly cynical.",
  "2hollis": "AI Summary: Emerging underground artist blending hyperpop and aggressive electronic rap into a chaotic, high-energy live show.",
  "¥ØU$UK€ ¥UK1MAT$U": "AI Summary: Legendary Japanese DJ known for unpredictable, wildly eclectic sets that mix everything from noise to club anthems.",
  "Aiko el Grupo": "AI Summary: High-energy Spanish punk-pop band praised for their incredibly fun, fast-paced, and sarcastic anthems.",
  "Ravyn Lenae": "AI Summary: R&B powerhouse. Reviewers consistently highlight her stunning vocal range and lush, neo-soul production.",
  "Massive Attack": "AI Summary: Trip-hop legends. Critics consistently hail their live shows as politically charged, visually stunning, and sonically massive.",
  "Bad Gyal": "AI Summary: A pioneer in the Spanish dancehall and reggaeton scene, praised for her high-energy performances and club-ready hits.",
  "Raly": "AI Summary: Exciting up-and-coming act bringing fresh rhythms and engaging stage presence.",
  "Geese": "AI Summary: Brooklyn post-punk band acclaimed for their unpredictable, sprawling, and fiercely energetic rock performances.",
  "Mac DeMarco": "AI Summary: The king of 'jangle-pop' and slacker rock, loved by fans and critics alike for his laid-back, goofy charm.",
  "TV Girl": "AI Summary: Indie pop favorites known for their sample-heavy, hypnotic grooves and sardonic lyrical themes.",
  "Overmono": "AI Summary: Electronic duo celebrated for their ecstatic UK bass and techno productions, earning rave reviews for their live sets.",
  "Sama Yax": "AI Summary: Dynamic DJ and producer known for weaving global rhythms and deep grooves into their sets.",
  "berlioz": "AI Summary: Rising electronic jazz artist whose smooth, lo-fi house beats have taken the internet by storm.",
  "Guedra Guedra": "AI Summary: Moroccan producer whose sets are an explosive celebration of North African rhythms and heavy club bass.",
  "Ahadadream": "AI Summary: UK club music heavyweight known for his infectious, drum-heavy DJ sets that guarantee a massive dancefloor.",
  "BAMBII": "AI Summary: Toronto DJ and producer praised for her exhilarating, genre-defying sets blending dancehall, jungle, and techno.",
  "Ben UFO": "AI Summary: Widely considered one of the best DJs in the world, renowned for his seamless, genre-spanning selections.",
  "Paus": "AI Summary: Portuguese experimental rock band featuring two drum kits, known for their powerful, rhythmic live shows.",
  "The New Eves": "AI Summary: UK folk-punk quartet praised for their raw, ritualistic, and deeply captivating performances.",
  "Agriculture": "AI Summary: 'Ecstatic black metal' band from Los Angeles, celebrated for their intensely emotional and uplifting heavy music.",
  "Florence Road": "AI Summary: A vibrant new artist bringing energetic hooks and undeniable indie charm.",
  "Melt-Banana": "AI Summary: Legendary Japanese noise-rock duo. Their live shows are famously frenetic, ear-splittingly loud, and incredibly precise.",
  "VVV [Trippin'you]": "AI Summary: Spanish neo-bakalao trio. Critics highlight their intense, dark, and highly energetic electronic punk shows.",
  "Muna Khaled": "AI Summary: An intriguing electronic act delivering atmospheric and deeply textured soundscapes.",
  "Toumba live": "AI Summary: Jordanian producer weaving traditional Levantine sounds into forward-thinking club music.",
  "Bclip": "AI Summary: Experimental club producer mixing Latin rhythms with heavy, aggressive electronic beats.",
  "iza tkm": "AI Summary: Innovative DJ bringing a fresh perspective to the underground club scene.",
  "DJ Playero": "AI Summary: A true pioneer of reggaeton, his sets are a masterclass in Latin dance music history and hype.",
  "xavisphone": "AI Summary: Emerging electronic act with a unique, internet-inspired sound.",
  "Proc Fiskal live": "AI Summary: Scottish producer known for his hyper-speed, incredibly intricate takes on grime and UK bass.",
  "Stein": "AI Summary: Delivering deep, resonant electronic grooves tailored for the late-night crowd.",
  "Rustie": "AI Summary: A hugely influential figure in maximalist electronic music, returning to deliver his signature euphoric drops.",
  "Zohar": "AI Summary: Experimental DJ and producer known for dark, brooding, and bass-heavy selections.",
  "Mina Galán": "AI Summary: Bringing a blend of intense electronic rhythms and atmospheric textures to the stage.",
  "Blood Orange": "AI Summary: Dev Hynes' acclaimed R&B project. Reviews praise his lush instrumentation and breathtakingly soulful performances.",
  "Alex G": "AI Summary: Indie rock cult hero. Critics adore his eclectic, lo-fi songwriting and unpredictable, mesmerizing live shows.",
  "Doja Cat": "AI Summary: Global pop/rap superstar. Her live performances are praised for their incredible choreography, stage design, and vocal talent.",
  "Hypnosis Therapy": "AI Summary: Exciting South Korean electronic/rap duo known for their futuristic, high-energy club anthems.",
  "Renaldo & Clara": "AI Summary: Catalan indie pop group celebrated for their delicate melodies and bittersweet songwriting.",
  "LaBlackie": "AI Summary: Rising Spanish rap artist known for her fierce flow, confident stage presence, and hard-hitting beats.",
  "Skullcrusher": "AI Summary: Ambient folk artist praised for her hauntingly beautiful vocals and deeply intimate songwriting.",
  "Rojuu": "AI Summary: Spanish emo-trap phenomenon with a massive cult following and wildly energetic, emotional live shows.",
  "Fcukers": "AI Summary: Rising NYC indie dance trio praised for their effortlessly cool, 90s-inspired house and pop fusion.",
  "Six Sex": "AI Summary: Argentinian reggaeton and club artist known for her unapologetic, hyper-energetic, and raunchy performances.",
  "Malibu": "AI Summary: French ambient producer whose sets are described as breathtakingly beautiful, cinematic, and deeply emotional.",
  "Brìghde Chaimbeul": "AI Summary: Award-winning Scottish piper who creates hypnotic, drone-heavy ambient folk music.",
  "New York": "AI Summary: Captivating indie act bringing raw, energetic sounds reminiscent of the city's classic rock revival.",
  "neska": "AI Summary: Intriguing electronic act with a focus on immersive, rhythmic soundscapes.",
  "Oli XL Live": "AI Summary: Swedish producer known for his fragmented, fascinating, and highly original take on UK dance music.",
  "Anthony Naples": "AI Summary: Revered house music producer and DJ. His sets are a masterclass in deep, atmospheric grooves.",
  "Bombificadas": "AI Summary: Local Spanish act delivering energetic, punk-infused pop.",
  "Paco Te Quiero": "AI Summary: Fun, irreverent Spanish indie-pop band known for their highly entertaining live shows.",
  "Dharmacide": "AI Summary: Madrid-based shoegaze and post-punk band delivering massive walls of reverb-drenched sound.",
  "Annahstasia": "AI Summary: Soulful folk singer-songwriter whose stunning vocal performances command absolute silence from the crowd.",
  "mark william lewis": "AI Summary: UK indie artist praised for his hushed, incredibly intimate, and poetic songwriting.",
  "Einstürzende Neubauten": "AI Summary: Industrial music pioneers. Their legendary live shows feature custom-built instruments and avant-garde intensity.",
  "Merzbow": "AI Summary: The godfather of Japanese noise music. A Merzbow live set is a famous test of endurance and sonic extremity.",
  "Pavvla": "AI Summary: Catalan indie-pop artist known for her dark, electronic-tinged folk and emotive vocals.",
  "Buscabulla": "AI Summary: Puerto Rican duo celebrated for their effortlessly cool, psychedelic Caribbean dream-pop.",
  "Ralphie Choo": "AI Summary: Genre-defying Spanish artist mixing flamenco, pop, and electronic music into critically acclaimed, chaotic live shows.",
  "Amaarae": "AI Summary: Afro-fusion star. Reviewers praise her whispering vocal style and incredibly slick, genre-bending pop anthems.",
  "PinkPantheress": "AI Summary: Breakout star known for her byte-sized, nostalgic UK garage and drum-n-bass pop tracks that dominate both TikTok and critical lists.",
  "KI/KI": "AI Summary: Dutch techno DJ whose high-BPM, trance-infused sets are legendary for their relentless, euphoric energy.",
  "NewDad": "AI Summary: Irish indie rock band acclaimed for their moody, 90s-inspired alternative rock and shoegaze textures.",
  "Ethel Cain": "AI Summary: Southern gothic indie rock praised for its cinematic storytelling, dark Americana aesthetic, and her hauntingly powerful vocals.",
  "The Cure": "AI Summary: Goth-rock pioneers with a massive catalog. Reviews praise Robert Smith's enduring vocal prowess and their emotionally sweeping concerts.",
  "Slowdive": "AI Summary: Shoegaze titans whose ethereal, wall-of-sound live performances are often described as transcendent and deeply atmospheric.",
  "Addison Rae": "AI Summary: Pop artist who transitioned from viral fame to critical intrigue with her polished, self-aware alt-pop sound.",
  "Skrillex": "AI Summary: Electronic music visionary. His recent sets are praised for pushing genre boundaries and maintaining relentless crowd energy.",
  "Somos la Herencia": "AI Summary: Madrid post-punk outfit blending darkwave synths with aggressive, atmospheric rock.",
  "Rilo Kiley": "AI Summary: Beloved indie rock band. Fans adore Jenny Lewis's sharp lyrics and the band's emotionally resonant catalog.",
  "Role Model": "AI Summary: Alt-pop singer praised for his charismatic stage presence, catchy hooks, and relatable lyricism.",
  "Jade": "AI Summary: A highly anticipated solo performance bringing polished pop vocals and dynamic choreography.",
  "Viagra Boys": "AI Summary: Swedish post-punk outfit acclaimed for their chaotic, satirical, and aggressively fun live energy.",
  "Malena": "AI Summary: Up-and-coming DJ bringing a finely curated mix of electronic rhythms.",
  "Powder": "AI Summary: Japanese DJ and producer known for incredibly subtle, hypnotic, and emotionally nuanced house sets.",
  "Call Super": "AI Summary: Highly respected DJ praised for his technically flawless and endlessly surprising, genre-spanning mixes.",
  "DJ Koolt": "AI Summary: Uruguayan underground legend. His vinyl-only sets are a masterclass in deep, rolling house and techno.",
  "Roza Terenzi Live": "AI Summary: Australian producer delivering bouncy, retro-futuristic electro and breakbeat live sets.",
  "Aurora Halal": "AI Summary: Brooklyn-based techno producer known for her deep, psychedelic, and intensely immersive live hardware sets.",
  "Sama’ Abdulhadi": "AI Summary: Palestinian techno pioneer. Her DJ sets are famous worldwide for their massive, hard-hitting energy.",
  "Las Petunias": "AI Summary: Fun, energetic Spanish punk-pop trio with catchy melodies and relatable lyrics.",
  "Ósserp": "AI Summary: Brutal Catalan death metal/grindcore band. Their live shows are intense, aggressive, and highly technical.",
  "Water From Your Eyes": "AI Summary: Experimental pop duo praised for their deadpan delivery and brilliantly chaotic, unpredictable song structures.",
  "Shlohmo": "AI Summary: Influential electronic producer. His live shows blend dark, heavy bass with melancholic, guitar-driven textures.",
  "Kylesa": "AI Summary: Legendary sludge metal band returning to the stage, featuring dual drummers and massive, psychedelic riffs.",
  "Tiyumii": "AI Summary: A fresh electronic act setting the mood with deep, atmospheric beats.",
  "Dj Khalipha": "AI Summary: Exciting DJ bringing a mix of global club sounds and high-energy rhythms.",
  "GЯEG": "AI Summary: Mauritian DJ based in Paris, known for explosive sets blending dancehall, techno, and afro-club sounds.",
  "The Avalanches DJ Set": "AI Summary: Legendary sample-plunderers. Their DJ sets are a joyous, unpredictable celebration of music history.",
  "Loukeman": "AI Summary: Emerging electronic producer blending sample-heavy house with deep, emotional grooves.",
  "Brutalismus 3000": "AI Summary: Berlin duo mixing gabber, techno, and punk into incredibly intense, sweaty, and viral live performances.",
  "Brat Star DJ Set": "AI Summary: Versatile DJ known for chaotic, high-energy sets that jump from rap to hard techno seamlessly.",
  "Hannah Diamond (DJ)": "AI Summary: PC Music icon. Her DJ sets are a glittery, hyper-pop sugar rush filled with exclusive edits.",
  "Hekt": "AI Summary: Delivering hard-hitting, fast-paced electronic sets for the late-night club crowd.",
  "deBasement": "AI Summary: Underground collective bringing raw, uncompromising techno and bass music.",
  "Debit": "AI Summary: Mexican-American producer acclaimed for blending indigenous instrumentation with experimental club music.",
  "Dave P.": "AI Summary: Making Time legend. His DJ sets are a masterclass in euphoric, futuristic electronic dance music.",
  ".bd.": "AI Summary: Intriguing experimental artist pushing the boundaries of sonic texture.",
  "Juicy Bae": "AI Summary: Spanish R&B and trap artist celebrated for her smooth vocals and commanding stage presence.",
  "Texas Is The Reason": "AI Summary: 90s emo legends. Their live shows are highly emotional, nostalgic, and incredibly cathartic.",
  "Disobey": "AI Summary: High-energy punk act bringing rebellious anthems and a wild mosh pit.",
  "fakemink": "AI Summary: Exciting electronic producer delivering forward-thinking club edits.",
  "Cara Delevingne": "AI Summary: The model-turned-artist brings a highly anticipated, exclusive performance to the festival.",
  "Underground Resistance": "AI Summary: Detroit techno royalty. Their live shows are politically charged, technically brilliant, and deeply soulful.",
  "Joan La Barbara": "AI Summary: Avant-garde composer and vocalist. Her performances are celebrated for their breathtaking vocal techniques.",
  "Matmos": "AI Summary: Experimental electronic duo famous for creating fascinating music out of incredibly unusual recorded samples.",
  "Rashad Becker": "AI Summary: Mastering engineer and producer delivering complex, highly textured, and abstract electronic performances.",
  "Mohammad Reza Mortazavi": "AI Summary: Iranian percussion master. His solo tombak performances are mind-bendingly complex and mesmerizing.",
  "Marc Piñol": "AI Summary: Barcelona club legend. His DJ sets are vast, eclectic journeys through the finest house and techno.",
  "Iglooghost": "AI Summary: UK producer known for hyperactive, wildly complex electronic music paired with a rich, fantastical visual world.",
  "Amiga Date Cuenta": "AI Summary: Relatable, fun, and energetic Spanish indie pop.",
  "Perfecto Miserable": "AI Summary: Shoegaze and dream-pop act delivering nostalgic, reverb-heavy melodies.",
  "Corte!": "AI Summary: Sharp, punchy post-punk with aggressive basslines and biting lyrics.",
  "SVSTO": "AI Summary: Blending electronic pop with indie sensibilities for a highly danceable set.",
  "These New Puritans": "AI Summary: Acclaimed art-rock band. Critics praise their orchestral, highly ambitious, and dramatic live performances.",
  "Beverly Glenn-Copeland and Elizabeth Copeland": "AI Summary: Legendary ambient folk artist. Reviews highlight the profound, tear-jerking spirituality of his live shows.",
  "Anna von Hausswolff": "AI Summary: Swedish musician famous for playing massive church organs, creating terrifyingly beautiful, doom-laden music.",
  "Jimena Amarillo": "AI Summary: Rising Spanish star praised for her deeply honest, romantic, and lo-fi pop-folk songwriting.",
  "Grace Ives": "AI Summary: Brooklyn synth-pop artist. Critics love her punchy, infectious, and incredibly fun solo live performances.",
  "rusowsky": "AI Summary: Key figure in the Spanish bedroom pop scene, blending classical training with lo-fi beats and autotune.",
  "Dijon": "AI Summary: R&B/indie artist. Reviews constantly praise his incredibly raw, emotionally unhinged, and spontaneous live band performances.",
  "Peggy Gou": "AI Summary: Global DJ superstar blending house and techno with infectious pop sensibilities, praised for her impeccable crowd control.",
  "Big Thief": "AI Summary: Indie folk-rock darlings. Critics adore Adrianne Lenker's raw, poetic songwriting and the band's intense, emotive chemistry.",
  "My Bloody Valentine": "AI Summary: The absolute masters of shoegaze. Their live shows are famously, beautifully, and physically deafening.",
  "Gorillaz": "AI Summary: Damon Albarn's virtual band is renowned for their eclectic genre-hopping and visually spectacular, guest-heavy live shows.",
  "Bestia Bebé": "AI Summary: Argentine indie rock band known for their infectious melodies and stadium-ready rock anthems.",
  "Sudan Archives": "AI Summary: Singer and violinist whose live shows are celebrated for their incredible swagger, musicianship, and R&B grooves.",
  "Ashnikko": "AI Summary: Alt-pop rapper. Fans adore her visually wild, unapologetic, and fiercely empowering live shows.",
  "Marina": "AI Summary: Pop royalty. Her performances are praised for her operatic vocals and incredibly loyal, energetic fanbase.",
  "Kneecap": "AI Summary: Irish hip-hop trio. Critics highlight their wildly energetic, rebellious, and politically charged bilingual performances.",
  "M8NSE": "AI Summary: Fresh electronic act delivering deep, bass-heavy club rhythms.",
  "Florentino b2b dj g2g": "AI Summary: A massive back-to-back set guaranteed to deliver high-energy reggaeton, club edits, and heavy bass.",
  "Safety Trance Live AV": "AI Summary: High-BPM reggaeton and techno fusion, paired with intense and chaotic visual art.",
  "Lechuga Zafiro & Verraco: Hyperverbena": "AI Summary: A special collaboration mixing forward-thinking Latin club sounds with intricate electronic percussion.",
  "mobilegirl": "AI Summary: Berlin DJ known for her playful, hyper-energetic blends of R&B, techno, and global club music.",
  "Mechatok Live": "AI Summary: Swedish producer creating glossy, emotional, and hyper-melodic electronic pop and club music.",
  "u.r.trax Live": "AI Summary: Parisian techno prodigy delivering fast, trippy, and relentless live hardware sets.",
  "JASSS": "AI Summary: Acclaimed DJ and producer. Her sets are a masterclass in dark, industrial, and unpredictable techno.",
  "The Sophs": "AI Summary: Charming indie rock with earworm melodies and a great live dynamic.",
  "Smerz": "AI Summary: Norwegian duo blending R&B vocals with stark, minimal, and experimental electronic production.",
  "Lambrini Girls": "AI Summary: Brighton punk band. Their live shows are famous for being fiercely political, chaotic, and incredibly fun.",
  "Femtanyl": "AI Summary: Breakout hyperpop and breakcore artist. Expect incredibly fast, aggressive, and internet-poisoned energy.",
  "Ninajirachi": "AI Summary: Australian producer delivering glossy, heavy, and meticulously sound-designed club pop.",
  "Curated by SONNY": "AI Summary: A special stage takeover featuring hand-picked, cutting-edge electronic and club artists.",
  "Barry B": "AI Summary: Rising Spanish artist blending indie rock with contemporary pop elements.",
  "Baxter Dury": "AI Summary: Suave, spoken-word indie rock. Reviewers love his sleazy, charming, and highly theatrical stage persona.",
  "Little Simz": "AI Summary: One of UK rap's brightest stars. Reviewers consistently award her perfect scores for her lyrical dexterity and grandiose live arrangements.",
  "The xx": "AI Summary: Known for their intimate, minimalist indie-pop. Critics often highlight the palpable chemistry and emotional vulnerability in their performances.",
  "Ven’nus": "AI Summary: Catalan artist bringing soft, electronic-infused indie pop with a beautifully melancholic edge.",
  "Depresión Sonora": "AI Summary: Spanish post-punk. Fans resonate deeply with their danceable, gloomy anthems about modern life.",
  "Gelli Haha": "AI Summary: Quirky, unpredictable, and highly entertaining alternative pop.",
  "Touché Amoré": "AI Summary: Post-hardcore legends. Their live shows are famously passionate, emotionally devastating, and full of crowd-surfing.",
  "Joey Valence & Brae": "AI Summary: High-energy rap duo heavily inspired by 90s boom-bap and the Beastie Boys. Incredibly fun live.",
  "Nick León Live": "AI Summary: Miami producer known for his massive global club hits. His live sets blend Latin percussion with deep techno.",
  "Ecco2k": "AI Summary: Drain Gang member. His ethereal, experimental pop performances are highly stylized and fiercely beloved by fans.",
  "res_": "AI Summary: Delivering deep, cerebral techno for the dedicated warehouse crowd.",
  "DJ Marcelle": "AI Summary: Legendary Dutch DJ who plays with three turntables, mixing the most bizarre and chaotic records into a danceable set.",
  "Shackleton Live": "AI Summary: UK bass pioneer. His live sets are dark, polyrhythmic, and intensely psychedelic tribal journeys.",
  "Beatrice M.": "AI Summary: Bringing deep, rolling basslines and intricate electronic textures.",
  "A Guy Called Gerald Live": "AI Summary: Acid house and jungle royalty. A masterclass in vintage, hardware-driven dance music.",
  "DJ Nobu": "AI Summary: Japanese techno master. Reviewers revere his highly psychedelic, deeply hypnotic, and flawlessly mixed sets.",
  "Greta": "AI Summary: A fresh voice in indie pop, bringing smooth vocals and engaging stage presence.",
  "BLOND:ISH": "AI Summary: Tech-house superstar. Her sets are known for their positive energy, uplifting vocals, and massive festival drops.",
  "Joseph Capriati": "AI Summary: Italian techno giant. Famous for his marathon sets and driving, relentless big-room grooves.",
  "Carl Cox": "AI Summary: A true legend of house and techno. Critics and fans revere his unparalleled mixing skills and joyous stage presence."
};

lineup = lineup.map(band => {
  const desc = descriptions[band.band] || `AI Summary: Rising act bringing a highly anticipated mix of rhythm, melody, and unique festival energy.`;
  return { ...band, description: desc };
});

const newContent = `const lineup = ${JSON.stringify(lineup, null, 2)};\n`;
fs.writeFileSync('lineup.js', newContent);
console.log('Successfully enriched all lineup bands.');
