const lineup = [
  { "id": "wed-1", "day": "Wednesday, June 3", "band": "Ouineta", "time": "17:45", "stage": "Parc del Fòrum" },
  { "id": "wed-2", "day": "Wednesday, June 3", "band": "Yard Act", "time": "18:55", "stage": "Parc del Fòrum" },
  { "id": "wed-3", "day": "Wednesday, June 3", "band": "Guitarricadelafuente", "time": "20:15", "stage": "Parc del Fòrum" },
  { "id": "wed-4", "day": "Wednesday, June 3", "band": "Wet Leg", "time": "21:55", "stage": "Parc del Fòrum" },
  { "id": "thu-1", "day": "Thursday, June 4", "band": "Mourn", "time": "18:00", "stage": "Aperol Island of Joy" },
  { "id": "thu-2", "day": "Thursday, June 4", "band": "Gara Durán", "time": "19:20", "stage": "Aperol Island of Joy" },
  { "id": "thu-3", "day": "Thursday, June 4", "band": "Dani Dicostas", "time": "20:40", "stage": "Aperol Island of Joy" },
  { "id": "thu-4", "day": "Thursday, June 4", "band": "Cameron Winter", "time": "17:00", "stage": "Auditori Rockdelux" },
  { "id": "thu-5", "day": "Thursday, June 4", "band": "Lucrecia Dalt", "time": "19:00", "stage": "Auditori Rockdelux" },
  { "id": "thu-6", "day": "Thursday, June 4", "band": "caroline", "time": "20:30", "stage": "Auditori Rockdelux" },
  { "id": "thu-7", "day": "Thursday, June 4", "band": "Panda Bear", "time": "22:00", "stage": "Auditori Rockdelux" },
  { "id": "thu-8", "day": "Thursday, June 4", "band": "Gisela João", "time": "17:15", "stage": "Cupra" },
  { "id": "thu-9", "day": "Thursday, June 4", "band": "Men I Trust", "time": "18:50", "stage": "Cupra" },
  { "id": "thu-10", "day": "Thursday, June 4", "band": "Oklou", "time": "20:50", "stage": "Cupra" },
  { "id": "thu-11", "day": "Thursday, June 4", "band": "Father John Misty", "time": "23:00", "stage": "Cupra" },
  { "id": "thu-12", "day": "Thursday, June 4", "band": "2hollis", "time": "01:35", "stage": "Cupra" },
  { "id": "thu-13", "day": "Thursday, June 4", "band": "¥ØU$UK€ ¥UK1MAT$U", "time": "04:30", "stage": "Cupra" },
  { "id": "thu-14", "day": "Thursday, June 4", "band": "Aiko el Grupo", "time": "17:30", "stage": "Estrella Damm" },
  { "id": "thu-15", "day": "Thursday, June 4", "band": "Ravyn Lenae", "time": "19:35", "stage": "Estrella Damm" },
  { "id": "thu-61", "day": "Thursday, June 4", "band": "Massive Attack", "time": "22:05", "stage": "Estrella Damm" },
  { "id": "thu-16", "day": "Thursday, June 4", "band": "Bad Gyal", "time": "01:20", "stage": "Estrella Damm" },
  { "id": "thu-17", "day": "Thursday, June 4", "band": "Raly", "time": "18:00", "stage": "Occident" },
  { "id": "thu-18", "day": "Thursday, June 4", "band": "Geese", "time": "19:45", "stage": "Occident" },
  { "id": "thu-19", "day": "Thursday, June 4", "band": "Mac DeMarco", "time": "21:55", "stage": "Occident" },
  { "id": "thu-20", "day": "Thursday, June 4", "band": "TV Girl", "time": "00:30", "stage": "Occident" },
  { "id": "thu-21", "day": "Thursday, June 4", "band": "Overmono", "time": "03:00", "stage": "Occident" },
  { "id": "thu-22", "day": "Thursday, June 4", "band": "Sama Yax", "time": "18:00", "stage": "Plenitude" },
  { "id": "thu-23", "day": "Thursday, June 4", "band": "berlioz", "time": "19:00", "stage": "Plenitude" },
  { "id": "thu-24", "day": "Thursday, June 4", "band": "Guedra Guedra", "time": "23:25", "stage": "Plenitude" },
  { "id": "thu-25", "day": "Thursday, June 4", "band": "Ahadadream", "time": "00:25", "stage": "Plenitude" },
  { "id": "thu-26", "day": "Thursday, June 4", "band": "BAMBII", "time": "02:00", "stage": "Plenitude" },
  { "id": "thu-27", "day": "Thursday, June 4", "band": "Ben UFO", "time": "03:00", "stage": "Plenitude" },
  { "id": "thu-28", "day": "Thursday, June 4", "band": "Paus", "time": "17:15", "stage": "Port" },
  { "id": "thu-29", "day": "Thursday, June 4", "band": "The New Eves", "time": "18:55", "stage": "Port" },
  { "id": "thu-30", "day": "Thursday, June 4", "band": "Agriculture", "time": "20:55", "stage": "Port" },
  { "id": "thu-31", "day": "Thursday, June 4", "band": "Florence Road", "time": "23:00", "stage": "Port" },
  { "id": "thu-32", "day": "Thursday, June 4", "band": "Melt-Banana", "time": "01:30", "stage": "Port" },
  { "id": "thu-33", "day": "Thursday, June 4", "band": "VVV [Trippin'you]", "time": "03:40", "stage": "Port" },
  { "id": "thu-34", "day": "Thursday, June 4", "band": "Muna Khaled", "time": "18:00", "stage": "Cupra Pulse" },
  { "id": "thu-35", "day": "Thursday, June 4", "band": "Toumba live", "time": "19:00", "stage": "Cupra Pulse" },
  { "id": "thu-36", "day": "Thursday, June 4", "band": "Bclip", "time": "20:00", "stage": "Cupra Pulse" },
  { "id": "thu-37", "day": "Thursday, June 4", "band": "iza tkm", "time": "21:00", "stage": "Cupra Pulse" },
  { "id": "thu-38", "day": "Thursday, June 4", "band": "DJ Playero", "time": "22:00", "stage": "Cupra Pulse" },
  { "id": "thu-39", "day": "Thursday, June 4", "band": "xavisphone", "time": "23:00", "stage": "Cupra Pulse" },
  { "id": "thu-40", "day": "Thursday, June 4", "band": "Proc Fiskal live", "time": "00:00", "stage": "Cupra Pulse" },
  { "id": "thu-41", "day": "Thursday, June 4", "band": "Stein", "time": "01:00", "stage": "Cupra Pulse" },
  { "id": "thu-42", "day": "Thursday, June 4", "band": "Rustie", "time": "02:00", "stage": "Cupra Pulse" },
  { "id": "thu-43", "day": "Thursday, June 4", "band": "Zohar", "time": "03:30", "stage": "Cupra Pulse" },
  { "id": "thu-44", "day": "Thursday, June 4", "band": "Mina Galán", "time": "05:00", "stage": "Cupra Pulse" },
  { "id": "thu-45", "day": "Thursday, June 4", "band": "Blood Orange", "time": "18:20", "stage": "Revolut" },
  { "id": "thu-46", "day": "Thursday, June 4", "band": "Alex G", "time": "20:50", "stage": "Revolut" },
  { "id": "thu-47", "day": "Thursday, June 4", "band": "Doja Cat", "time": "23:30", "stage": "Revolut" },
  { "id": "thu-48", "day": "Thursday, June 4", "band": "Hypnosis Therapy", "time": "16:30", "stage": "Schwarzkopf" },
  { "id": "thu-49", "day": "Thursday, June 4", "band": "Renaldo & Clara", "time": "18:05", "stage": "Schwarzkopf" },
  { "id": "thu-50", "day": "Thursday, June 4", "band": "LaBlackie", "time": "19:55", "stage": "Schwarzkopf" },
  { "id": "thu-51", "day": "Thursday, June 4", "band": "Skullcrusher", "time": "21:55", "stage": "Schwarzkopf" },
  { "id": "thu-52", "day": "Thursday, June 4", "band": "Rojuu", "time": "00:25", "stage": "Schwarzkopf" },
  { "id": "thu-53", "day": "Thursday, June 4", "band": "Fcukers", "time": "02:40", "stage": "Schwarzkopf" },
  { "id": "thu-54", "day": "Thursday, June 4", "band": "Six Sex", "time": "04:35", "stage": "Schwarzkopf" },
  { "id": "thu-55", "day": "Thursday, June 4", "band": "Malibu", "time": "22:00", "stage": "The Levi's Warehouse" },
  { "id": "thu-56", "day": "Thursday, June 4", "band": "Brìghde Chaimbeul", "time": "23:05", "stage": "The Levi's Warehouse" },
  { "id": "thu-57", "day": "Thursday, June 4", "band": "New York", "time": "00:10", "stage": "The Levi's Warehouse" },
  { "id": "thu-58", "day": "Thursday, June 4", "band": "neska", "time": "01:15", "stage": "The Levi's Warehouse" },
  { "id": "thu-59", "day": "Thursday, June 4", "band": "Oli XL Live", "time": "02:20", "stage": "The Levi's Warehouse" },
  { "id": "thu-60", "day": "Thursday, June 4", "band": "Anthony Naples", "time": "03:25", "stage": "The Levi's Warehouse" },
  { "id": "fri-1", "day": "Friday, June 5", "band": "Bombificadas", "time": "18:00", "stage": "Aperol Island of Joy" },
  { "id": "fri-2", "day": "Friday, June 5", "band": "Ouineta", "time": "19:20", "stage": "Aperol Island of Joy" },
  { "id": "fri-3", "day": "Friday, June 5", "band": "Paco Te Quiero", "time": "20:40", "stage": "Aperol Island of Joy" },
  { "id": "fri-4", "day": "Friday, June 5", "band": "Dharmacide", "time": "22:00", "stage": "Aperol Island of Joy" },
  { "id": "fri-5", "day": "Friday, June 5", "band": "Annahstasia", "time": "16:30", "stage": "Auditori Rockdelux" },
  { "id": "fri-6", "day": "Friday, June 5", "band": "mark william lewis", "time": "18:00", "stage": "Auditori Rockdelux" },
  { "id": "fri-7", "day": "Friday, June 5", "band": "Einstürzende Neubauten", "time": "19:30", "stage": "Auditori Rockdelux" },
  { "id": "fri-8", "day": "Friday, June 5", "band": "Merzbow", "time": "21:00", "stage": "Auditori Rockdelux" },
  { "id": "fri-9", "day": "Friday, June 5", "band": "Pavvla", "time": "17:15", "stage": "Cupra" },
  { "id": "fri-10", "day": "Friday, June 5", "band": "Buscabulla", "time": "18:50", "stage": "Cupra" },
  { "id": "fri-11", "day": "Friday, June 5", "band": "Ralphie Choo", "time": "20:55", "stage": "Cupra" },
  { "id": "fri-12", "day": "Friday, June 5", "band": "Amaarae", "time": "23:20", "stage": "Cupra" },
  { "id": "fri-13", "day": "Friday, June 5", "band": "PinkPantheress", "time": "01:45", "stage": "Cupra" },
  { "id": "fri-14", "day": "Friday, June 5", "band": "KI/KI", "time": "04:10", "stage": "Cupra" },
  { "id": "fri-15", "day": "Friday, June 5", "band": "NewDad", "time": "17:40", "stage": "Estrella Damm" },
  { "id": "fri-16", "day": "Friday, June 5", "band": "Ethel Cain", "time": "19:45", "stage": "Estrella Damm" },
  { "id": "fri-17", "day": "Friday, June 5", "band": "The Cure", "time": "22:15", "stage": "Estrella Damm" },
  { "id": "fri-18", "day": "Friday, June 5", "band": "Slowdive", "time": "18:15", "stage": "Revolut" },
  { "id": "fri-19", "day": "Friday, June 5", "band": "Addison Rae", "time": "21:00", "stage": "Revolut" },
  { "id": "fri-20", "day": "Friday, June 5", "band": "Skrillex", "time": "01:00", "stage": "Revolut" },
  { "id": "fri-21", "day": "Friday, June 5", "band": "Somos la Herencia", "time": "18:00", "stage": "Occident" },
  { "id": "fri-22", "day": "Friday, June 5", "band": "Rilo Kiley", "time": "19:50", "stage": "Occident" },
  { "id": "fri-23", "day": "Friday, June 5", "band": "Role Model", "time": "22:00", "stage": "Occident" },
  { "id": "fri-24", "day": "Friday, June 5", "band": "Jade", "time": "00:30", "stage": "Occident" },
  { "id": "fri-25", "day": "Friday, June 5", "band": "Viagra Boys", "time": "02:55", "stage": "Occident" },
  { "id": "fri-26", "day": "Friday, June 5", "band": "Malena", "time": "18:00", "stage": "Plenitude" },
  { "id": "fri-27", "day": "Friday, June 5", "band": "Powder", "time": "19:30", "stage": "Plenitude" },
  { "id": "fri-28", "day": "Friday, June 5", "band": "Call Super", "time": "21:00", "stage": "Plenitude" },
  { "id": "fri-29", "day": "Friday, June 5", "band": "DJ Koolt", "time": "22:30", "stage": "Plenitude" },
  { "id": "fri-30", "day": "Friday, June 5", "band": "Roza Terenzi Live", "time": "00:00", "stage": "Plenitude" },
  { "id": "fri-31", "day": "Friday, June 5", "band": "Aurora Halal", "time": "01:00", "stage": "Plenitude" },
  { "id": "fri-32", "day": "Friday, June 5", "band": "Sama’ Abdulhadi", "time": "02:30", "stage": "Plenitude" },
  { "id": "fri-33", "day": "Friday, June 5", "band": "Las Petunias", "time": "17:20", "stage": "Port" },
  { "id": "fri-34", "day": "Friday, June 5", "band": "Ósserp", "time": "19:00", "stage": "Port" },
  { "id": "fri-35", "day": "Friday, June 5", "band": "Water From Your Eyes", "time": "21:00", "stage": "Port" },
  { "id": "fri-36", "day": "Friday, June 5", "band": "Shlohmo", "time": "23:15", "stage": "Port" },
  { "id": "fri-37", "day": "Friday, June 5", "band": "Kylesa", "time": "01:35", "stage": "Port" },
  { "id": "fri-38", "day": "Friday, June 5", "band": "Tiyumii", "time": "18:00", "stage": "Cupra Pulse" },
  { "id": "fri-39", "day": "Friday, June 5", "band": "Dj Khalipha", "time": "19:00", "stage": "Cupra Pulse" },
  { "id": "fri-40", "day": "Friday, June 5", "band": "GЯEG", "time": "20:00", "stage": "Cupra Pulse" },
  { "id": "fri-41", "day": "Friday, June 5", "band": "The Avalanches DJ Set", "time": "21:00", "stage": "Cupra Pulse" },
  { "id": "fri-42", "day": "Friday, June 5", "band": "Loukeman", "time": "22:00", "stage": "Cupra Pulse" },
  { "id": "fri-43", "day": "Friday, June 5", "band": "Brutalismus 3000", "time": "23:00", "stage": "Cupra Pulse" },
  { "id": "fri-44", "day": "Friday, June 5", "band": "Brat Star DJ Set", "time": "00:00", "stage": "Cupra Pulse" },
  { "id": "fri-45", "day": "Friday, June 5", "band": "Hannah Diamond (DJ)", "time": "01:00", "stage": "Cupra Pulse" },
  { "id": "fri-46", "day": "Friday, June 5", "band": "Hekt", "time": "02:00", "stage": "Cupra Pulse" },
  { "id": "fri-47", "day": "Friday, June 5", "band": "deBasement", "time": "02:45", "stage": "Cupra Pulse" },
  { "id": "fri-48", "day": "Friday, June 5", "band": "Debit", "time": "03:45", "stage": "Cupra Pulse" },
  { "id": "fri-49", "day": "Friday, June 5", "band": "Dave P.", "time": "04:45", "stage": "Cupra Pulse" },
  { "id": "fri-50", "day": "Friday, June 5", "band": ".bd.", "time": "16:35", "stage": "Schwarzkopf" },
  { "id": "fri-51", "day": "Friday, June 5", "band": "Juicy Bae", "time": "18:05", "stage": "Schwarzkopf" },
  { "id": "fri-52", "day": "Friday, June 5", "band": "Texas Is The Reason", "time": "19:50", "stage": "Schwarzkopf" },
  { "id": "fri-53", "day": "Friday, June 5", "band": "Disobey", "time": "22:05", "stage": "Schwarzkopf" },
  { "id": "fri-54", "day": "Friday, June 5", "band": "fakemink", "time": "00:25", "stage": "Schwarzkopf" },
  { "id": "fri-55", "day": "Friday, June 5", "band": "Cara Delevingne", "time": "02:30", "stage": "Schwarzkopf" },
  { "id": "fri-56", "day": "Friday, June 5", "band": "Underground Resistance", "time": "04:05", "stage": "Schwarzkopf" },
  { "id": "fri-57", "day": "Friday, June 5", "band": "Joan La Barbara", "time": "22:00", "stage": "The Levi's Warehouse" },
  { "id": "fri-58", "day": "Friday, June 5", "band": "Matmos", "time": "22:50", "stage": "The Levi's Warehouse" },
  { "id": "fri-59", "day": "Friday, June 5", "band": "Rashad Becker", "time": "23:40", "stage": "The Levi's Warehouse" },
  { "id": "fri-60", "day": "Friday, June 5", "band": "Mohammad Reza Mortazavi", "time": "00:45", "stage": "The Levi's Warehouse" },
  { "id": "fri-61", "day": "Friday, June 5", "band": "Marc Piñol", "time": "02:20", "stage": "The Levi's Warehouse" },
  { "id": "fri-62", "day": "Friday, June 5", "band": "Iglooghost", "time": "03:55", "stage": "The Levi's Warehouse" },
  { "id": "sat-1", "day": "Saturday, June 6", "band": "Amiga Date Cuenta", "time": "18:00", "stage": "Aperol Island of Joy" },
  { "id": "sat-2", "day": "Saturday, June 6", "band": "Perfecto Miserable", "time": "19:20", "stage": "Aperol Island of Joy" },
  { "id": "sat-3", "day": "Saturday, June 6", "band": "Corte!", "time": "20:40", "stage": "Aperol Island of Joy" },
  { "id": "sat-4", "day": "Saturday, June 6", "band": "SVSTO", "time": "22:00", "stage": "Aperol Island of Joy" },
  { "id": "sat-5", "day": "Saturday, June 6", "band": "These New Puritans", "time": "18:00", "stage": "Auditori Rockdelux" },
  { "id": "sat-6", "day": "Saturday, June 6", "band": "Beverly Glenn-Copeland and Elizabeth Copeland", "time": "19:30", "stage": "Auditori Rockdelux" },
  { "id": "sat-7", "day": "Saturday, June 6", "band": "Anna von Hausswolff", "time": "21:00", "stage": "Auditori Rockdelux" },
  { "id": "sat-8", "day": "Saturday, June 6", "band": "Jimena Amarillo", "time": "17:10", "stage": "Cupra" },
  { "id": "sat-9", "day": "Saturday, June 6", "band": "Grace Ives", "time": "18:10", "stage": "Cupra" },
  { "id": "sat-10", "day": "Saturday, June 6", "band": "rusowsky", "time": "21:15", "stage": "Cupra" },
  { "id": "sat-11", "day": "Saturday, June 6", "band": "Dijon", "time": "23:20", "stage": "Cupra" },
  { "id": "sat-12", "day": "Saturday, June 6", "band": "Knocked Loose", "time": "01:35", "stage": "Cupra" },
  { "id": "sat-13", "day": "Saturday, June 6", "band": "Peggy Gou", "time": "04:15", "stage": "Cupra" },
  { "id": "sat-14", "day": "Saturday, June 6", "band": "Big Thief", "time": "19:40", "stage": "Estrella Damm" },
  { "id": "sat-15", "day": "Saturday, June 6", "band": "My Bloody Valentine", "time": "22:05", "stage": "Estrella Damm" },
  { "id": "sat-16", "day": "Saturday, June 6", "band": "Gorillaz", "time": "01:15", "stage": "Estrella Damm" },
  { "id": "sat-17", "day": "Saturday, June 6", "band": "Bestia Bebé", "time": "17:50", "stage": "Occident" },
  { "id": "sat-18", "day": "Saturday, June 6", "band": "Sudan Archives", "time": "19:00", "stage": "Occident" },
  { "id": "sat-19", "day": "Saturday, June 6", "band": "Ashnikko", "time": "20:15", "stage": "Occident" },
  { "id": "sat-20", "day": "Saturday, June 6", "band": "Marina", "time": "00:40", "stage": "Occident" },
  { "id": "sat-21", "day": "Saturday, June 6", "band": "Kneecap", "time": "03:00", "stage": "Occident" },
  { "id": "sat-22", "day": "Saturday, June 6", "band": "M8NSE", "time": "18:00", "stage": "Plenitude" },
  { "id": "sat-23", "day": "Saturday, June 6", "band": "Florentino b2b dj g2g", "time": "19:30", "stage": "Plenitude" },
  { "id": "sat-24", "day": "Saturday, June 6", "band": "Safety Trance Live AV", "time": "21:35", "stage": "Plenitude" },
  { "id": "sat-25", "day": "Saturday, June 6", "band": "Lechuga Zafiro & Verraco: Hyperverbena", "time": "22:30", "stage": "Plenitude" },
  { "id": "sat-26", "day": "Saturday, June 6", "band": "mobilegirl", "time": "23:45", "stage": "Plenitude" },
  { "id": "sat-27", "day": "Saturday, June 6", "band": "Mechatok Live", "time": "01:15", "stage": "Plenitude" },
  { "id": "sat-28", "day": "Saturday, June 6", "band": "u.r.trax Live", "time": "02:05", "stage": "Plenitude" },
  { "id": "sat-29", "day": "Saturday, June 6", "band": "JASSS", "time": "02:55", "stage": "Plenitude" },
  { "id": "sat-30", "day": "Saturday, June 6", "band": "The Sophs", "time": "18:50", "stage": "Port" },
  { "id": "sat-31", "day": "Saturday, June 6", "band": "Smerz", "time": "20:55", "stage": "Port" },
  { "id": "sat-32", "day": "Saturday, June 6", "band": "Lambrini Girls", "time": "23:10", "stage": "Port" },
  { "id": "sat-33", "day": "Saturday, June 6", "band": "Femtanyl", "time": "01:30", "stage": "Port" },
  { "id": "sat-34", "day": "Saturday, June 6", "band": "Ninajirachi", "time": "03:40", "stage": "Port" },
  { "id": "sat-35", "day": "Saturday, June 6", "band": "Curated by SONNY", "time": "18:00", "stage": "Cupra Pulse" },
  { "id": "sat-36", "day": "Saturday, June 6", "band": "Barry B", "time": "17:15", "stage": "Revolut" },
  { "id": "sat-37", "day": "Saturday, June 6", "band": "Baxter Dury", "time": "18:30", "stage": "Revolut" },
  { "id": "sat-38", "day": "Saturday, June 6", "band": "Little Simz", "time": "20:50", "stage": "Revolut" },
  { "id": "sat-39", "day": "Saturday, June 6", "band": "The xx", "time": "23:40", "stage": "Revolut" },
  { "id": "sat-40", "day": "Saturday, June 6", "band": "Ven’nus", "time": "16:35", "stage": "Schwarzkopf" },
  { "id": "sat-41", "day": "Saturday, June 6", "band": "Depresión Sonora", "time": "18:00", "stage": "Schwarzkopf" },
  { "id": "sat-42", "day": "Saturday, June 6", "band": "Gelli Haha", "time": "19:45", "stage": "Schwarzkopf" },
  { "id": "sat-52", "day": "Saturday, June 6", "band": "Touché Amoré", "time": "22:00", "stage": "Schwarzkopf" },
  { "id": "sat-43", "day": "Saturday, June 6", "band": "Joey Valence & Brae", "time": "00:25", "stage": "Schwarzkopf" },
  { "id": "sat-44", "day": "Saturday, June 6", "band": "Nick León Live", "time": "02:50", "stage": "Schwarzkopf" },
  { "id": "sat-45", "day": "Saturday, June 6", "band": "Ecco2k", "time": "04:35", "stage": "Schwarzkopf" },
  { "id": "sat-46", "day": "Saturday, June 6", "band": "res_", "time": "22:00", "stage": "The Levi's Warehouse" },
  { "id": "sat-47", "day": "Saturday, June 6", "band": "DJ Marcelle", "time": "23:00", "stage": "The Levi's Warehouse" },
  { "id": "sat-48", "day": "Saturday, June 6", "band": "Shackleton Live", "time": "00:30", "stage": "The Levi's Warehouse" },
  { "id": "sat-49", "day": "Saturday, June 6", "band": "Beatrice M.", "time": "01:30", "stage": "The Levi's Warehouse" },
  { "id": "sat-50", "day": "Saturday, June 6", "band": "A Guy Called Gerald Live", "time": "03:00", "stage": "The Levi's Warehouse" },
  { "id": "sat-51", "day": "Saturday, June 6", "band": "DJ Nobu", "time": "04:00", "stage": "The Levi's Warehouse" },
  { "id": "sun-1", "day": "Sunday, June 7", "band": "Greta", "time": "15:00", "stage": "Parc del Fòrum" },
  { "id": "sun-2", "day": "Sunday, June 7", "band": "BLOND:ISH", "time": "16:30", "stage": "Parc del Fòrum" },
  { "id": "sun-3", "day": "Sunday, June 7", "band": "Joseph Capriati", "time": "18:00", "stage": "Parc del Fòrum" },
  { "id": "sun-4", "day": "Sunday, June 7", "band": "Carl Cox", "time": "20:00", "stage": "Parc del Fòrum" }
];
